---
- hosts: all
  become: yes
  vars:
    hostname:
      enabled: False
  roles:
  - kubeadm_install

- hosts: master_nodes
  become: yes
  vars:
    hostname:
      enabled: False
  roles:
  - kubeadm_setup
  tasks:
  - name: Register IP
    shell: "echo {{ ansible_default_ipv4.address }}"
    register: K8S_MASTER_NODE_IP


- hosts:
  - join_masters
  - workers
  become: yes
  gather_facts: false
  tasks:
    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
        
    - name: Turnoff swapp
      shell: swapoff -a


- hosts: join_masters
  become: yes
  gather_facts: false
  tasks:
    - name: "Kubeadm join"
      shell: |
        kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }} \
          --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }} \
          192.168.15.50:6443 --control-plane --certificate-key {{ hostvars['K8S_TOKEN_HOLDER']['certkey'] }}


- hosts: workers
  become: yes
  tasks:
  - name: "Kubeadm join"
    shell: |
      kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }} \
        --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }} \
        192.168.15.50:6443
