---
- name: Enable Modules
  shell: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    microk8s enable {{ item }}
  when: True
  loop:
    - dns
    - ingress
    - storage
    # - rbac
    # - fluentd
    # - prometheus
  args:
    executable: /bin/bash


- name: Enable K8s Dashboard
  shell: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    microk8s enable dashboard
  when: k8s_dashboard|default(False)|bool == True
  args:
    executable: /bin/bash
