# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  # config.ssh.username   = "root"  
  
  config.vm.box         = "hashicorp/bionic64"
  config.vm.hostname    = "shounen"
  config.vm.define "base"
  config.vm.network "public_network",
    use_dhcp_assigned_default_route: true

  config.vm.box_check_update = false

  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
      vb.name = "fenixpure"
  #   # Customize the amount of memory on the VM:
      vb.memory = "2048"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update && apt-get full-upgrade -y && apt-get install -yq curl wget git python3 python3-pip jq nfs-server nfs-common
     cat>>/home/vagrant/.ssh/authorized_keys<<EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCl5/GfejqIb2XVjKiTRGWsWFKe24mKPT7YSLAC+D0r00PYjxhm5jnQBIn67UmfYQgcS1hoB7S3TRAborvXiuQIGOeVo9fxpwg+WnnLpCfJl1L6F7zGoQRWOGRDjffD87rk8VDy50I0tk+Zmka2q6g1JiGkXECkR/JBDj8aZfVj8BvSpZPuZ7M5pVc7gt7vy4vzHWXNf4MurIpSefQVEX0UHTTa7P9KKDyC4R3+gqpD/QWUoe06fTq5F7uPWgAUmR0eM59tEez+zf7SJUD2AD7+ziRVSPe/V3de7Xfupxsz2sBHclntGC0oVyfcyrpCdPRTtMlFgikDpDehr45CNHTrp/xS82D+xI/nv6aGaWcdJy7Jem0P7Y1Hf93KicR+vTDMQVfxULIYh1J2IWRb6CISlaPjREGGeE8lbq4kqfhShbhsG40kXQ+hxtLi6bd7WBL8F9HbrqDdO4kE9YYzWjCjyz4dAYYtZvXvM0G0Iv3Wjfo3GwPn2Zz0JQCKltZj/+dLiDkB8LogFsAd6XA52rsTcFREA3jffRkV1r6gX3jKqlPT7yQs/+Q5m/9PI1FtmkSXy1RAShJcw51BEyh75OWdXYkmOu6+NTKF0Eo6R92L0uOxuqbOjd25X2WpbmxqI4wGc2qiXxV9AvGQxoMbC2w6Y9c3RtoS3kXIHqfrqfm9OQ== felipefonsecarocha@gmail.com
EOF
SHELL
end
