---
# tasks file for config_docker
- name: add docker  apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker latest version
  apt:
    pkg:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
    state: latest

- name: add group and user for docker
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
    
- name: Install docker-compose
  pip:
    name: docker-compose
    executable: pip3