---
- hosts: all
  become: yes
  roles:
  - config_ubuntu
  - config_mick8s
# - config_docker

- hosts: master_nodes
  become: yes
  gather_facts: false
  vars: 
    join_token: teste
  tasks:
    - name: Get token join master
      shell: microk8s add-node -l 600 | microk8s add-node | grep 192 | cut -d' ' -f 4
      register: join_token 

    - name: Set token
      set_fact:
        join_token: "{{ join_token.stdout }}"
        cacheable: yes

    - name: Token
      debug: 
        var: join_token

    - name: Register dummy host with variable   
      add_host:
        name: "master_nodes"
        join_token: "{{ join_token }}"


- hosts: join_masters
  become: yes
  gather_facts: false
  tasks:
    - name: Joining to the Cluster
      debug:
        var: hostvars['master_nodes']

    - name: Join to Cluster
      shell: "microk8s join {{ hostvars['master_nodes']['join_token'] }}"
      when: hostvars['master_nodes']['join_token'] is defined

  