Vagrant.configure("2") do |config|
  config.vm.box         = "hashicorp/bionic64"
  config.vm.box_check_update = true

  config.vm.define "lab1" do |lab1|
    lab1.vm.network "public_network", ip: "192.168.15.71", bridge: "enp1s0"
  end
  config.vm.define "lab2" do |lab2|
    lab2.vm.network "public_network",  ip: "192.168.15.72", bridge: "enp1s0"
  end
  config.vm.define "lab3" do |lab3|
    lab3.vm.network "public_network",  ip: "192.168.15.73", bridge: "enp1s0"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    ansible.host_vars = {
      "lab1" => {"hostname" => "lab1"},
      "lab2" => {"hostname" => "lab2"},
      "lab3" => {"hostname" => "lab3"},
    }
  end
end
