Vagrant.configure("2") do |config|
  # config.vm.box         = "hashicorp/bionic64"
  config.vm.box         = "generic/ubuntu2004"
  config.vm.box_check_update = true
  N = 3
  (1..N).each do |machine_id|
    config.vm.define "machine#{machine_id}" do |machine|
      machine.vm.hostname = "machine#{machine_id}"
      machine.vm.network "public_network", ip: "192.168.15.#{70+machine_id}", bridge: "enp1s0"
      # Define machine size
      machine.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 1
      end
      

      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if machine_id == N
      #   machine.vm.provision "ansible_local" do |ansible_local|
      #   ansible_local.playbook = "provisioning/main.yml"
      #   ansible_local.galaxy_role_file = "provisioning/requirements.yml"
      #   ansible_local.galaxy_roles_path = "provisioning/roles/"
      #   ansible_local.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
      # end
        machine.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit = "all"
          ansible.playbook = "provisioning/main.yml"
          ansible.groups = {
            "masters" => [],
            "masters:children" => ["mac1","mac2","mac3"],
            "master_nodes" => [],
            "master_nodes:children" => ["mac1"],
            "join_masters" => [],
            "join_masters:children" => ["mac2","mac3"],
            "workers" => [],
            "all:children" => ["masters","workers"],
            "all:vars" => {"ansible_python_interpreter" => "/usr/bin/python3",
               "user" => "vagrant"},
            "mac1" => ["machine1"],
            "mac2" => ["machine2"],
            "mac3" => ["machine3"],
            "mac1:vars" => {"hostname" => "master1"},
            "mac2:vars" => {"hostname" => "master2"},
            "mac3:vars" => {"hostname" => "master3"}
          }
        end
      end
    end
  end
end
